
[simulation]
execution_time = 40
total_nodes = 10 # n
slow_nodes_percent = 20 # z0
low_cpu_nodes_percent = 20 # z1

[node]
min_neighbors = 3
max_neighbors = 6

[transaction]
size = 1 # in KBs
mean_interarrival_time_sec = 10 # Ttx

[network]
min_light_prop_delay = 0.010 # in seconds, pij-min
max_light_prop_delay = 0.500 # in seconds, pij-max
slow_node_link_speed = 100 # in Mbps, cij-min
fast_node_link_speed = 5 # in Mbps, cij-max
queuing_delay_constant = 96 # in kbits, used for dij

[mining]
